using Photons;
using SangoUtils.UnityDevelopToolKits;
using SceneGameObjects;
using System.IO;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;

namespace Editors
{
    [CustomEditor(typeof(ObjectManager))]
    internal class ObjectManagerInspector : Editor
    {
        private const string Dom_Declaration = "/// <summary>\r\n/// This is Generated by a Tools, you should avoid make direct modify it.\r\n/// </summary>\r\n";

        private ObjectManager _manager;

        private SerializedProperty _objEnvsParent;
        private SerializedProperty _objNpcsParent;

        private SerializedProperty _objPrefabs;

        private void OnEnable()
        {
            serializedObject.Update();

            _manager = (ObjectManager)target;

            _objEnvsParent = serializedObject.FindProperty("_objEnvsParent");
            _objNpcsParent = serializedObject.FindProperty("_objNpcsParent");

            _objPrefabs = serializedObject.FindProperty("_objPrefabs");
        }

        public override void OnInspectorGUI()
        {
            EditorGUI.BeginChangeCheck();

            EditorGUILayout.PropertyField(_objEnvsParent);
            EditorGUILayout.PropertyField(_objNpcsParent);

            EditorGUILayout.PropertyField(_objPrefabs);

            if (EditorGUI.EndChangeCheck())
                serializedObject.ApplyModifiedProperties();

            EditorGUILayout.Space();
            if (GUILayout.Button("Generate Names Source File"))
                GenerateNamesSourceFile(_manager);
        }

        private void GenerateNamesSourceFile(ObjectManager manager)
        {
            var codeWriter = new CodeWriter();

            var generatedDirectoryPath = Path.Combine(Application.dataPath, "Generateds", "Runtime");
            var typeNameSourceText = "partial class ObjectManager";

            codeWriter.AppendLine(Dom_Declaration);

            codeWriter.AppendLine("namespace Photons");
            codeWriter.BeginBlock();

            codeWriter.AppendLine(typeNameSourceText);
            codeWriter.BeginBlock();

            if (!Directory.Exists(generatedDirectoryPath))
                Directory.CreateDirectory(generatedDirectoryPath);

            AppendPublicField(codeWriter, _manager);

            codeWriter.EndBlock();
            codeWriter.EndBlock();

            var sourceText = codeWriter.ToString();

            File.WriteAllText(Path.Combine(generatedDirectoryPath, "ObjectManager.g.cs"), sourceText);

            codeWriter.Clear();
            codeWriter = null;

            CompilationPipeline.RequestScriptCompilation();
        }

        private void AppendPublicField(in CodeWriter codeWriter, in ObjectManager manager)
        {
            string sourceText;

            codeWriter.AppendLine("public class ObjEnvNames");
            codeWriter.BeginBlock();
            for (int i = 0; i < ((GameObject)_objEnvsParent.objectReferenceValue).transform.childCount; i++)
            {
                var item = ((GameObject)_objEnvsParent.objectReferenceValue).transform.GetChild(i);
                if (item.TryGetComponent<EnvObjectBehaviour>(out var behaviour))
                {
                    var itemName = Validator.ValidateVariableName(item.name);
                    sourceText = "public const string " + itemName + " = \"" + item.name + "\";";
                    codeWriter.AppendLine(sourceText);
                }
            }
            codeWriter.EndBlock();

            codeWriter.AppendLine();

            codeWriter.AppendLine("public class ObjPrefabNames");
            codeWriter.BeginBlock();
            for (int i = 0; i < _objPrefabs.arraySize; i++)
            {
                var item = _objPrefabs.GetArrayElementAtIndex(i).objectReferenceValue as GameObject;
                var itemName = Validator.ValidateVariableName(item.name);
                sourceText = "public const string " + itemName + " = \"" + item.name + "\";";
                codeWriter.AppendLine(sourceText);
            }
            codeWriter.EndBlock();
        }
    }
}
