 /// <summary>
/// This is Generated by a Tools, you should avoid make direct modify it.
/// </summary>

 namespace Photons
 {
     partial class ObjectManager
     {
         public class ObjEnvNames
         {
             public const string GlassCube = "GlassCube";
             public const string Ghost_animation_Rokid = "Ghost_animation_Rokid";
         }

         public class ObjPrefabNames
         {
             public const string StoneSphere = "StoneSphere";
         }
     }
 }
