 /// <summary>
/// This is Generated by a Tools, you should avoid make direct modify it.
/// </summary>

 namespace Photons
 {
     partial class ObjectManager
     {
         public class ObjGrabableNames
         {
             public const int Ghost_animation_Rokid = 1001000;
         }
     }
 }
