/// <summary>
/// This is Generated by a Tools, you should avoid make direct modify it.
/// </summary>

public static class Tags
{

    public const string Untagged = "Untagged";

    public const string Respawn = "Respawn";

    public const string Finish = "Finish";

    public const string EditorOnly = "EditorOnly";

    public const string MainCamera = "MainCamera";

    public const string Player = "Player";

    public const string GameController = "GameController";

}

public static class Layers
{

    public const string Default = "0";

    public const string TransparentFX = "1";

    public const string Ignore_Raycast = "2";

    public const string Water = "4";

    public const string UI = "5";

}